### PR TITLE
Revisions 2017 07

### PR DESCRIPTION
**Pull request by levyj**
Pending review, these are the final changes to the new requirements that should be publicized shortly for implementation in the 9-2017 data due to be reported in 10-2017.

### CODE REVIEW

**Comment by tomschenkjr** [comment]
For `Shared ID Trip` in `T15`, do we need to specify that the ID should be unique across the entire span of reporting. Or, does it only need to be unique within reporting periods?

Also, on this field, I think we can omit "although the City of Chicago reserves the right to apply further restrictions" since that is the case for all of these fields.

**Comment by levyj** [comment]
For `T15`, it should be unique across the entire span of reporting since the reporting periods are more of an operational concept than one inherent to the data. We do, of course, run analyses by month reasonably often but also run analyses by other time periods.  Given that there may be potential for ambiguity, I definitely am in favor of clarifying.

On the right to apply further restrictions, that is a valid point, of course. I can see some value in highlighting it here since there is a higher likelihood. We are giving the TNPs a bit more flexibility than with other fields.  We think that will work but there is the possibility that one or more of them will, entirely in good faith, select a coding system that causes a problem for us and we will need to tell them to change it.  That said, I have no real objection to dropping that text.  Would you still like me to do so, @tomschenkjr?

**Comment by tomschenkjr** [comment]
@levyj - let's drop the modification text.

Let's also clarify the uniqueness requirement. Not so much for the current team issuing the reports, but will be more useful as new people report to us.

Otherwise, looks good. Let me know when you update the commit and I'll approve.

**Comment by levyj** [comment]
@tomschenkjr - Done, on both counts.

**Pull request merged**
